### ISSUE TITLE
Warning after updating mongodb dependency.

### ISSUE THREAD

**Issue by rojasTob** [winstonjs/winston-mongodb#90] opened 2017-02-15 15:11 UTC
Hello everyone.
I've installed the latest version of winston-mongodb. I've noticed that the version of mongodb from your package has updated from 2.1.4 version to 2.2.24 version. For that reason I think I got this warning:

**the server/replset/mongos options are deprecated, all their options are supported at the top level of the options object [poolSize,ssl,sslValidate,sslCA,sslCert,sslKey,sslPass,autoReconnect,noDelay,keepAlive,connectTimeoutMS,socketTimeoutMS,reconnectTries,reconnectInterval,ha,haInterval,replicaSet,secondaryAcceptableLatencyMS,acceptableLatencyMS,connectWithNoPrimary,authSource,w,wtimeout,j,forceServerObjectId,serializeFunctions,ignoreUndefined,raw,promoteLongs,bufferMaxEntries,readPreference,pkFactory,promiseLibrary,readConcern,maxStalenessSeconds,loggerLevel,logger,promoteValues,promoteBuffers,promoteLongs,domainsEnabled,keepAliveInitialDelay,checkServerIdentity,validateOptions]**

How can I solve this? Any idea?

Thanks!!

**Comment by chrispstephens** [comment] 2017-02-17 00:48
+1 on the issue. A workaround is to pass in a promise object which will be resolved with pre-connected db object, rather than MongoDB connection uri.

```
var db = require('mongodb').MongoClient.connect('localhost/mydb')
winston.add(winston.transports.MongoDB, {db: db})
```

**Comment by skuntze** [comment] 2017-02-17 07:57
+1 thanks for sharing the workaround! Works for me! @chrispstephens

**Comment by jskrzypek** [comment] 2017-02-28 10:49
+1

@chrispstephens your workaround fixed the errors listed above, but we're still getting some errors that look like this:

```
the options [connector] is not supported
the options [url] is not supported
the options [allowExtendedOperators] is not supported
the options [debug] is not supported
the options [safe] is not supported
the options [connector] is not supported
the options [url] is not supported
the options [allowExtendedOperators] is not supported
the options [debug] is not supported
the options [safe] is not supported
the options [connector] is not supported
the options [url] is not supported
the options [allowExtendedOperators] is not supported
the options [debug] is not supported
the options [safe] is not supported
the options [hostname] is not supported
the options [port] is not supported
the options [database] is not supported
```
Any ideas?

**Comment by netusco** [comment] 2017-02-28 11:29
@chrispstephens the new pull request #91 fixes the warning when using db uri

**Comment by 39dotyt** [comment] 2017-03-01 18:42
@netusco thank you for the PR.
Merged, published. Checkout version 2.0.8.

**Comment by 39dotyt** [comment] 2017-03-01 18:44
@jskrzypek How do you work with winston-mongodb?
Can you provide a minimal working script which reproduces the issue?

**Closed by 39dotyt** 2017-03-01 18:44 UTC
Labels: trivial
