### ISSUE TITLE
Meta with ObjectId can't be save when ObjectId contains a buffer

### ISSUE THREAD

**Issue by HugoPoi** [winstonjs/winston-mongodb#85] opened 2016-12-13 14:49 UTC
This works.
`winston.log('error', 'test', { test: mongodb.ObjectId('111111111111') });`

And this doesn't work :
`winston.log('error', 'test', { test: mongodb.ObjectId('313131313131313131313131') });`

Tested with
winston 2.3.0
winston-mongodb 2.0.6
mongodb 2.2.5

**Comment by santanu-biswas** [comment] 2016-12-16 13:29
I am getting the same problem! 

I tried to debug and I think it is the call to [prepareMetaData](https://github.com/winstonjs/winston-mongodb/blob/master/lib/helpers.js#L16) from [here](https://github.com/winstonjs/winston-mongodb/blob/master/lib/winston-mongodb.js#L210) that is altering the ObjectId and making it an invalid ObjectId for MongoDB.

**Comment by 39dotyt** [comment] 2016-12-16 14:08
@HugoPoi @santanu-biswas Issue confirmed. Will be fixed ASAP.

**Comment by j13z** [comment] 2016-12-26 21:13
For me modifying `prepareMetaData` in [helpers.js](https://github.com/winstonjs/winston-mongodb/blob/master/lib/helpers.js#L67) as follows fixes the issue:

```
const ObjectID = require('mongodb').ObjectID;
// …

// Line 67:
// if (typeof value === 'object') {
if (typeof value === 'object' && !(value instanceof ObjectID)) {
```

Can anyone confirm this?

**Comment by HugoPoi** [comment] 2016-12-28 10:08
@j13z confirm your sample code fix the issue.

**Comment by steve-p-com** [comment] 2017-01-12 09:37
Is there any ETA when this fix is likely to reach the npm registry? Or should I just revert to an earlier version? Thanks.

**Comment by 39dotyt** [comment] 2017-01-12 10:02
@j13z thanks for the fix. @steve-p-com  Will review and merge today.

**Comment by 39dotyt** [comment] 2017-01-13 06:52
Merged. Published. Thank you.

**Closed by 39dotyt** 2017-01-13 06:52 UTC
Labels: bug, critical

**Comment by dtiemann83** [comment] 2017-10-27 19:43
This issue seems to have returned. I'm seeing it in v3.0.1

**Comment by rvanmil** [comment] 2017-11-21 15:16
This seems to be an issue with winston itself. See https://github.com/winstonjs/winston/issues/611 and https://github.com/winstonjs/winston/issues/955
It looks like the workaround for now is to call `toString()` on ObjectID's (with length 24; there is no problem when the length is 12 because those aren't Buffers).
